import React,{useEffect,useMemo,useRef,useState} from 'react';
import {AlertCircle,Check,LoaderCircle,ReceiptText,X} from 'lucide-react';

const api=async(url,options={})=>{const response=await fetch(url,{...options,headers:{'content-type':'application/json'}}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'操作失敗');return data};
function Person({person,size=32}){return person.pictureUrl?<img className="avatar" src={person.pictureUrl} alt={person.displayName} style={{width:size,height:size}}/>:<span className="avatar initial" style={{width:size,height:size,background:'#1f9d69'}} aria-label={person.displayName}>{person.displayName.slice(0,1)}</span>}
function Modal({children,close}){const dialogRef=useRef(null),closeRef=useRef(close),returnFocus=useRef(document.activeElement);closeRef.current=close;useEffect(()=>{const dialog=dialogRef.current,focusable='button:not([disabled]), a[href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])';const initialTimer=setTimeout(()=>{if(dialog&&!dialog.contains(document.activeElement))dialog.querySelector(focusable)?.focus()},0);const onKeyDown=event=>{if(event.key==='Escape'){event.preventDefault();closeRef.current();return}if(event.key!=='Tab'||!dialog)return;const items=[...dialog.querySelectorAll(focusable)].filter(item=>item.getClientRects().length);if(!items.length)return;const first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};document.addEventListener('keydown',onKeyDown);return()=>{clearTimeout(initialTimer);document.removeEventListener('keydown',onKeyDown);returnFocus.current?.focus?.()}},[]);return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div ref={dialogRef} className="modal real-modal advanced-modal" role="dialog" aria-modal="true" aria-label="共同支出表單"><button type="button" className="modal-x" onClick={close} aria-label="關閉共同支出表單"><X/></button>{children}</div></div>}

export function AdvancedExpenseModal({group,expense=null,close,done}){
  const people=group.members.filter(x=>!x.isFund),payers=people;
  const storedShares=expense?.shares||[],storedPayments=expense?.payments||[],shareAmounts=storedShares.map(x=>Math.abs(Number(x.amountCents))),looksEqual=shareAmounts.length>0&&Math.max(...shareAmounts)-Math.min(...shareAmounts)<=1;
  const [kind,setKind]=useState(expense?.amountCents<0?'refund':'expense'),[title,setTitle]=useState(expense?.title||''),[amount,setAmount]=useState(expense?Math.abs(expense.amountCents)/100:''),[category,setCategory]=useState(expense?.category||'餐飲'),[payMode,setPayMode]=useState(storedPayments.length>1?'multiple':'single'),[payerId,setPayerId]=useState(storedPayments[0]?.userId||payers[0]?.id),[payerAmounts,setPayerAmounts]=useState(Object.fromEntries(storedPayments.map(x=>[x.userId,Math.abs(x.amountCents)/100]))),[mode,setMode]=useState(expense&&!looksEqual?'exact':'equal'),[selected,setSelected]=useState(expense?storedShares.map(x=>x.userId):people.map(x=>x.id)),[values,setValues]=useState(Object.fromEntries(storedShares.map(x=>[x.userId,Math.abs(x.amountCents)/100]))),[busy,setBusy]=useState(false),[attempted,setAttempted]=useState(false),[error,setError]=useState('');
  const total=Number(amount||0),toggle=id=>setSelected(old=>old.includes(id)?old.filter(x=>x!==id):[...old,id]);
  const payerTotal=Object.values(payerAmounts).reduce((s,v)=>s+Number(v||0),0),valueTotal=selected.reduce((s,id)=>s+Number(values[id]||0),0),blankCount=selected.filter(id=>!Number(values[id]||0)).length;
  const validationError=useMemo(()=>{if(!title.trim())return '請先填寫項目名稱';if(total<=0)return '總金額必須大於 0';if(!selected.length)return '請至少選擇一位分攤成員';if(payMode==='multiple'&&payerTotal!==total)return `付款加總需要是 ${total.toLocaleString()} 元，目前是 ${payerTotal.toLocaleString()} 元`;if(mode==='exact'&&valueTotal!==total)return '每人指定金額的加總必須等於總金額';if(mode==='hybrid'&&(valueTotal>=total||blankCount===0))return '指定金額後，必須保留至少一人分攤剩餘金額';if(mode==='weights'&&selected.some(id=>Number(values[id]||1)<=0))return '每位成員的份數必須大於 0';return ''},[title,total,selected,payMode,payerTotal,mode,valueTotal,blankCount,values]);
  const submit=async e=>{e.preventDefault();if(busy)return;setAttempted(true);if(validationError){setError('');return}setBusy(true);setError('');try{const payload={kind,title,amount:total,category,splitMode:mode,participantIds:selected};if(payMode==='single')payload.payerId=payerId;else payload.payers=payers.filter(p=>Number(payerAmounts[p.id])>0).map(p=>({userId:p.id,amount:Number(payerAmounts[p.id])}));if(mode==='exact')payload.shares=selected.map(userId=>({userId,amount:Number(values[userId]||0)}));if(mode==='hybrid')payload.fixedShares=selected.filter(id=>Number(values[id])>0).map(userId=>({userId,amount:Number(values[userId])}));if(mode==='weights')payload.weights=selected.map(userId=>({userId,weight:Number(values[userId]||1)}));await api(expense?`/api/groups/${group.id}/expenses/${expense.id}`:`/api/groups/${group.id}/expenses`,{method:expense?'PATCH':'POST',body:JSON.stringify(payload)});done()}catch(err){setError(err.message);setBusy(false)}};
  const valueLabel=mode==='weights'?'份數／權重':'負擔金額';
  const splitHelp={equal:'所有已選成員平均分攤，尾差會自動分配。',exact:'逐一輸入每位成員應負擔的確切金額。',hybrid:'先指定部分金額，剩餘金額由留空成員平均分攤。',weights:'依住宿天數、家庭人數等份數比例分攤。'}[mode];
  const displayError=error||(attempted?validationError:'');
return <Modal close={close}>
  <div className="kind-toggle" role="group" aria-label="紀錄類型"><button type="button" aria-pressed={kind==='expense'} className={kind==='expense'?'active':''} onClick={()=>setKind('expense')}>一般支出</button><button type="button" aria-pressed={kind==='refund'} className={kind==='refund'?'active refund':''} onClick={()=>setKind('refund')}>退款／退押金</button></div>
  <h2>{expense?'修改支出':kind==='expense'?'新增共同支出':'記錄一筆退款'}</h2>
  <p className="modal-copy">先記錄款項，再確認付款人與分攤方式。所有成員會立即看到更新。</p>
  <form onSubmit={submit} noValidate>
    <label>項目名稱 <span className="required-mark" aria-hidden="true">*</span><input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder={kind==='expense'?'例如：民宿尾款':'例如：民宿退押金'} required aria-invalid={attempted&&!title.trim()}/><small className="field-help">使用旅伴都能辨識的名稱，日後比較容易查找。</small></label>
    <div className="form-two"><label>{kind==='expense'?'總金額':'退款金額'} <span className="required-mark" aria-hidden="true">*</span><input type="number" min="1" step="1" inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="NT$ 0" required aria-invalid={attempted&&total<=0}/></label><label>分類<select value={category} onChange={e=>setCategory(e.target.value)}><option>餐飲</option><option>住宿</option><option>交通</option><option>購物</option><option>其他</option></select></label></div>
    <fieldset className="form-section"><legend>{kind==='expense'?'誰先付款？':'誰收到退款？'}</legend><div className="mini-toggle" role="group" aria-label="付款人數"><button type="button" aria-pressed={payMode==='single'} className={payMode==='single'?'active':''} onClick={()=>setPayMode('single')}>單人</button><button type="button" aria-pressed={payMode==='multiple'} className={payMode==='multiple'?'active':''} onClick={()=>setPayMode('multiple')}>多人湊款</button></div>{payMode==='single'?<label className="select-field">付款人<select value={payerId} onChange={e=>setPayerId(e.target.value)}>{payers.map(p=><option value={p.id} key={p.id}>{p.displayName}</option>)}</select></label>:<div className="amount-rows">{payers.map(p=><div key={p.id}><Person person={p}/><span>{p.displayName}</span><label>NT$<input type="number" min="0" inputMode="numeric" value={payerAmounts[p.id]||''} onChange={e=>setPayerAmounts(old=>({...old,[p.id]:e.target.value}))} placeholder="0"/></label></div>)}<p className={payerTotal===total?'ok':''}>付款加總 {payerTotal.toLocaleString()}／{total.toLocaleString()}</p></div>}</fieldset>
    <fieldset className="form-section"><legend>怎麼分攤？</legend><div className="split-tabs" role="group" aria-label="分攤方式">{[['equal','平均'],['exact','指定金額'],['hybrid','指定＋均分'],['weights','比例／份數']].map(([id,label])=><button type="button" key={id} aria-pressed={mode===id} className={mode===id?'active':''} onClick={()=>setMode(id)}>{label}</button>)}</div><p className="split-help">{splitHelp}</p><div className="participant-heading"><b>參與成員</b><small>已選 {selected.length}／{people.length} 人</small></div><div className={'advanced-participants '+(mode!=='equal'?'with-values':'')}>{people.map(p=><div className={selected.includes(p.id)?'selected':''} key={p.id}><button type="button" aria-pressed={selected.includes(p.id)} onClick={()=>toggle(p.id)}><Person person={p}/><span>{p.displayName}</span>{selected.includes(p.id)&&<Check/>}</button>{selected.includes(p.id)&&mode!=='equal'&&<label>{valueLabel}<input type="number" min={mode==='weights'?'0.01':'0'} step={mode==='weights'?'0.1':'1'} inputMode="decimal" value={values[p.id]||''} onChange={e=>setValues(old=>({...old,[p.id]:e.target.value}))} placeholder={mode==='weights'?'1':mode==='hybrid'?'留空＝均分':'0'}/></label>}</div>)}</div>{mode==='exact'&&<div className={'share-summary '+(valueTotal===total?'balanced':'')}><span>已分配 NT$ {valueTotal.toLocaleString()}</span><b>還差 NT$ {(total-valueTotal).toLocaleString()}</b></div>}{mode==='hybrid'&&<div className={'share-summary '+(valueTotal<total&&blankCount?'balanced':'')}><span>指定 NT$ {valueTotal.toLocaleString()}</span><b>剩餘 NT$ {(total-valueTotal).toLocaleString()} 由 {blankCount} 人均分</b></div>}</fieldset>
    {displayError&&<p className="form-error" role="alert"><AlertCircle/>{displayError}</p>}
    <div className="form-actions sticky-actions"><button type="button" className="secondary-button" onClick={close} disabled={busy}>取消</button><button className="primary" disabled={busy}>{busy?<LoaderCircle/>:<ReceiptText/>}{busy?'儲存中…':expense?'儲存修改':kind==='refund'?'儲存退款':'儲存支出'}</button></div>
  </form>
</Modal>
}
