import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight, BarChart3, Bell, Check, ChevronRight, CircleDollarSign, Menu, Plus, ReceiptText, Search, Sparkles, Users, WalletCards, X} from 'lucide-react';
import './style.css';
import ProductApp from './ProductApp.jsx';

const people=[{name:'小羅',img:'/xiaoluo-avatar.png',color:'#1f9d69'},{name:'安安',initial:'安',color:'#ef8b5a'},{name:'阿哲',initial:'哲',color:'#6c72d9'}];
const seed=[
  {id:1,title:'東大門夜市晚餐',payer:'小羅',amount:1280,date:'今天 19:32',cat:'餐飲',members:3},
  {id:2,title:'民宿訂金',payer:'安安',amount:3600,date:'昨天 21:08',cat:'住宿',members:3},
  {id:3,title:'租車加油',payer:'阿哲',amount:950,date:'7月20日',cat:'交通',members:3},
];
function Brand({light=false}){return <div className={'brand '+(light?'light':'')}><span className="brandmark"><span>東</span></span><b>東大小羅</b></div>}
function Avatar({p,size=38}){return p.img?<img className="avatar" style={{width:size,height:size}} src={p.img}/>:<span className="avatar initial" style={{width:size,height:size,background:p.color}}>{p.initial}</span>}
function Home({enter}){return <div className="site">
  <nav><Brand/><div className="navlinks"><a href="#features">主打功能</a><a href="#how">使用方式</a><a href="#cases">使用案例</a></div><button className="ghost">登入</button><button className="primary small" onClick={enter}>開始分帳</button></nav>
  <main>
    <section className="hero"><div className="hero-copy"><span className="eyebrow"><Sparkles size={15}/> 旅行分帳，現在簡單多了</span><h1>一起出發，<br/><em>不用一起算到頭痛。</em></h1><p>東大小羅幫你記下每一筆共同花費，誰付了、誰該還，一眼就懂。旅行的回憶留給大家，算錢交給小羅。</p><div className="hero-actions"><button className="primary" onClick={enter}>免費建立群組 <ArrowRight size={18}/></button><span><Check size={17}/> 不用信用卡</span></div><div className="social"><div className="stack">{people.map((p,i)=><Avatar p={p} key={i} size={40}/>)}</div><b>已有 2,840+ 個旅伴<br/><small>把算錢交給小羅</small></b></div></div>
    <div className="hero-visual"><div className="sun"></div><div className="ticket"><span>TAITUNG TRIP</span><b>東大探險隊</b><small>3 位旅伴 · TWD</small></div><div className="phone"><div className="phone-head"><Brand/><Avatar p={people[0]} size={34}/></div><p className="muted">你目前的餘額</p><h2>應收 NT$ 1,260</h2><div className="mini-card"><span>🍜</span><div><b>東大門夜市</b><small>小羅先付</small></div><strong>NT$ 1,280</strong></div><div className="mini-card"><span>🏠</span><div><b>海邊民宿</b><small>安安先付</small></div><strong>NT$ 3,600</strong></div><button className="phone-add"><Plus/> 新增一筆</button></div><div className="float-note"><CircleDollarSign/><div><small>已簡化債務</small><b>少轉 2 次帳</b></div></div></div></section>
    <section className="proof"><span>不用再開計算機</span><span>不用催朋友匯款</span><span>不用下載 App</span><span>多幣別也能分</span></section>
    <section id="features" className="section"><span className="eyebrow">小羅的探險工具箱</span><h2>分帳該有的，剛剛好。</h2><p className="lead">少一點表格，多一點旅行。每個功能都為了讓你更快結清。</p><div className="features"><article className="big feature green"><div><span className="icon"><ReceiptText/></span><h3>新增一筆，比點餐還快</h3><p>輸入金額、選付款人，剩下交給小羅自動均分，也能自訂每個人的份額。</p></div><div className="receipt"><b>山海咖啡</b><h3>NT$ 780</h3><div className="split-row">分給 3 人 <span>每人 NT$ 260</span></div><button>儲存這筆支出</button></div></article><article className="feature"><span className="icon orange"><WalletCards/></span><h3>欠誰多少，一眼看懂</h3><p>即時更新每個人的餘額，結算時自動找出最少轉帳次數。</p><div className="balance-line"><Avatar p={people[1]} size={34}/><span>安安付給小羅</span><b>NT$ 1,260</b></div></article><article className="feature"><span className="icon blue"><BarChart3/></span><h3>旅行花在哪，都有答案</h3><p>餐飲、住宿、交通自動分類，掌握群組花費不用自己做表。</p><div className="bars"><i></i><i></i><i></i><i></i><i></i></div></article></div></section>
    <section id="how" className="section steps"><span className="eyebrow">三步就出發</span><h2>從揪團到結清，一路順。</h2><div className="stepgrid">{[['01','建立旅程','取個群組名稱，選擇主要幣別。'],['02','邀請旅伴','分享一條連結，朋友不用下載。'],['03','記帳與結算','共同支出即時同步，最後一鍵結清。']].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
    <section id="cases" className="cta"><img src="/xiaoluo-avatar.png"/><div><span className="eyebrow">準備好了嗎？</span><h2>下一趟旅行，讓小羅跟。</h2><p>免費建立第一個群組，30 秒開始分帳。</p></div><button className="dark" onClick={enter}>建立我的旅程 <ArrowRight/></button></section>
  </main><footer><Brand light/><p>為每一趟同行，算得清清楚楚。</p><span>© 2026 東大小羅</span></footer>
  </div>}

function App(){const [inside,setInside]=useState(false),[records,setRecords]=useState(seed),[modal,setModal]=useState(false),[title,setTitle]=useState(''),[amount,setAmount]=useState(''),[payer,setPayer]=useState('小羅'); const total=records.reduce((s,r)=>s+r.amount,0); const mine=useMemo(()=>records.reduce((s,r)=>s+(r.payer==='小羅'?r.amount:0),0)-total/3,[records,total]);
 const add=e=>{e.preventDefault();if(!title||!amount)return;setRecords([{id:Date.now(),title,payer,amount:Number(amount),date:'剛剛',cat:'其他',members:3},...records]);setTitle('');setAmount('');setModal(false)};
 if(!inside)return <Home enter={()=>setInside(true)}/>;
 return <div className="app-shell"><aside><Brand/><div className="user"><Avatar p={people[0]} size={48}/><div><b>嗨，小羅！</b><small>今天也開心探險</small></div></div><div className="side-title">我的旅程</div><button className="trip active"><span>🌊</span><div><b>東大探險隊</b><small>3 位旅伴</small></div></button><button className="newtrip"><Plus/> 建立新旅程</button><div className="side-menu"><button><Users/> 所有旅伴</button><button><Bell/> 提醒事項</button></div><button className="back" onClick={()=>setInside(false)}>← 回到首頁</button></aside>
 <div className="workspace"><header><button className="mobile-menu"><Menu/></button><div><small>我的旅程 /</small><h2>東大探險隊 🌊</h2></div><div className="header-actions"><button className="round"><Search/></button><div className="stack">{people.map((p,i)=><Avatar p={p} key={i} size={34}/>)}</div><button className="invite"><Users/> 邀請</button></div></header>
 <main className="dashboard"><section className="welcome"><div><span className="pill">2026 夏日旅行</span><h1>嗨，小羅！今天花了什麼？</h1><p>記下共同花費，旅伴的餘額會立刻更新。</p></div><img src="/xiaoluo-avatar.png"/></section>
 <div className="statgrid"><article className="stat"><span className="stat-icon green"><WalletCards/></span><div><small>我的餘額</small><h3 className={mine>=0?'positive':'negative'}>{mine>=0?'應收':'應付'} NT$ {Math.abs(mine).toLocaleString(undefined,{maximumFractionDigits:0})}</h3><p>{mine>=0?'大家總共欠你':'你還需要結清'}</p></div></article><article className="stat"><span className="stat-icon orange"><ReceiptText/></span><div><small>旅程總支出</small><h3>NT$ {total.toLocaleString()}</h3><p>{records.length} 筆共同花費</p></div></article><article className="stat settle"><div><small>聰明結算</small><h3>只需要 2 次轉帳</h3><p>小羅幫你把債務簡化好了</p></div><button>查看結算 <ChevronRight/></button></article></div>
 <section className="activity"><div className="section-head"><div><h2>最近支出</h2><p>東大探險隊的共同花費</p></div><button className="primary" onClick={()=>setModal(true)}><Plus/> 新增支出</button></div><div className="filters"><button className="active">全部</button><button>餐飲</button><button>住宿</button><button>交通</button></div><div className="record-list">{records.map(r=><article key={r.id}><span className="record-icon">{r.cat==='餐飲'?'🍜':r.cat==='住宿'?'🏠':r.cat==='交通'?'🚗':'🧾'}</span><div className="record-name"><b>{r.title}</b><small>{r.date} · {r.payer} 先付</small></div><div className="member-dots">{people.map((p,i)=><Avatar p={p} key={i} size={26}/>)}</div><div className="record-price"><b>NT$ {r.amount.toLocaleString()}</b><small>每人 NT$ {Math.round(r.amount/r.members).toLocaleString()}</small></div><button className="more">•••</button></article>)}</div></section></main></div>
 {modal&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setModal(false)}><form className="modal" onSubmit={add}><div className="modal-head"><div><span className="eyebrow">新增共同花費</span><h2>這次是誰先付？</h2></div><button type="button" className="round" onClick={()=>setModal(false)}><X/></button></div><label>項目名稱<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="例如：東大門夜市晚餐"/></label><label>金額<div className="money"><span>NT$</span><input type="number" min="1" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0"/></div></label><label>付款人<select value={payer} onChange={e=>setPayer(e.target.value)}>{people.map(p=><option key={p.name}>{p.name}</option>)}</select></label><div className="split-info"><Users/> 將由 3 位旅伴平均分攤</div><button className="primary wide">儲存支出 <ArrowRight/></button></form></div>}
 </div>}
createRoot(document.getElementById('root')).render(<ProductApp Home={Home}/>);
