import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {AlertCircle,ArrowRight,Check,CircleHelp,Clipboard,DoorOpen,History,Link2,LoaderCircle,LogOut,Pencil,Plus,ReceiptText,RefreshCcw,Settings2,Trash2,Users,WalletCards,X} from 'lucide-react';
import {AdvancedExpenseModal} from './AdvancedExpenseModal.jsx';

const api=async(url,options={})=>{const response=await fetch(url,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});if(response.status===401)throw Object.assign(new Error('unauthorized'),{status:401});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'操作失敗');return data};
const money=cents=>`NT$ ${Math.round(Number(cents||0)/100).toLocaleString()}`;
function Logo(){return <div className="brand"><span className="brandmark"><span>旅</span></span><span className="brand-lockup"><b>旅帳</b><small>TripTab</small></span></div>}
function Person({person,size=36}){return person?.isFund?<span className="avatar fund-avatar" style={{width:size,height:size}} aria-label={person.displayName||'公費'}><WalletCards/></span>:person?.pictureUrl?<img className="avatar" src={person.pictureUrl} alt={person.displayName||'成員頭像'} style={{width:size,height:size}} referrerPolicy="no-referrer"/>:<span className="avatar initial" style={{width:size,height:size,background:'#1f9d69'}} aria-label={person?.displayName||'成員'}>{person?.displayName?.slice(0,1)||'旅'}</span>}
function ExpenseCategory({expense}){const label=expense.amountCents<0?'退款':expense.category||'其他';return <span className={`record-icon category-${label}`} aria-label={`分類：${label}`}><ReceiptText/><small>{label.slice(0,1)}</small></span>}

export default function ProductApp({Home}){
  const [me,setMe]=useState(null),[groups,setGroups]=useState([]),[activeId,setActiveId]=useState(null),[group,setGroup]=useState(null),[loading,setLoading]=useState(true),[groupLoading,setGroupLoading]=useState(false),[groupError,setGroupError]=useState(''),[notice,setNotice]=useState(''),[showCreate,setShowCreate]=useState(false),[showExpense,setShowExpense]=useState(false),[editingExpense,setEditingExpense]=useState(null),[showInvite,setShowInvite]=useState(false);
  const inviteToken=location.pathname.startsWith('/invite/')?location.pathname.split('/')[2]:null;
  const refreshGroups=useCallback(async()=>{const list=await api('/api/groups');setGroups(list);setActiveId(current=>current||list[0]?.id||null);return list},[]);
  useEffect(()=>{api('/api/me').then(async user=>{setMe(user);const list=await refreshGroups();if(inviteToken){const joined=await api(`/api/invites/${encodeURIComponent(inviteToken)}/join`,{method:'POST'});setActiveId(joined.groupId);await refreshGroups();history.replaceState({},'', '/app');setNotice('已成功加入群組！')}}).catch(error=>{if(error.status===401&&inviteToken){const returnTo=location.pathname;location.replace(`/api/auth/line?returnTo=${encodeURIComponent(returnTo)}`);return}if(error.status!==401)setNotice(error.message)}).finally(()=>setLoading(false))},[]);
  const refreshGroup=useCallback(async()=>{if(!activeId){setGroup(null);setGroupError('');return}setGroupLoading(true);setGroupError('');try{setGroup(await api(`/api/groups/${activeId}`))}catch(error){setGroup(null);setGroupError(error.message);throw error}finally{setGroupLoading(false)}},[activeId]);
  useEffect(()=>{if(me&&activeId)refreshGroup().catch(()=>{})},[me,activeId,refreshGroup]);
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(timer)},[notice]);
  const login=()=>{const returnTo=inviteToken?location.pathname:'/app';location.href=`/api/auth/line?returnTo=${encodeURIComponent(returnTo)}`};
  const logout=async()=>{await api('/api/auth/logout',{method:'POST'});setMe(null);setGroups([]);setGroup(null);history.replaceState({},'','/')};
  const created=async data=>{setShowCreate(false);await refreshGroups();setActiveId(data.id);history.replaceState({},'','/app')};
  const expenseAdded=async()=>{setShowExpense(false);setEditingExpense(null);await refreshGroup()};
  const groupDeleted=async target=>{await api(`/api/groups/${target.id}`,{method:'DELETE'});const list=await api('/api/groups');setGroups(list);setGroup(null);setActiveId(list[0]?.id||null);setNotice(`已刪除群組「${target.name}」`)};
  const openNewExpense=()=>{setEditingExpense(null);setShowExpense(true)};
  if(loading)return <div className="page-loading"><LoaderCircle/><p>正在整理帳本…</p></div>;
  if(!me&&inviteToken)return <div className="page-loading"><LoaderCircle/><p>正在前往 LINE 登入並加入群組…</p></div>;
  if(!me)return <Home enter={login}/>;
  return <div className="real-app">
    <aside className="real-side" aria-label="主要導覽">
      <Logo/>
      <div className="login-user"><Person person={me} size={46}/><div><b>{me.displayName}</b><small>LINE 帳號已連結</small></div></div>
      <div className="side-label">我的群組</div>
      <div className="group-switcher">{groups.map(item=><button className={activeId===item.id?'active':''} aria-current={activeId===item.id?'page':undefined} key={item.id} onClick={()=>setActiveId(item.id)}><span className="group-icon"><WalletCards/></span><div><b>{item.name}</b><small>{item.memberCount} 位成員</small></div></button>)}</div>
      <button className="new-group" onClick={()=>setShowCreate(true)}><Plus/> 建立新群組</button>
      <div className="side-footer"><small>旅帳 TripTab</small><button className="logout" onClick={logout}><LogOut/> 登出</button></div>
    </aside>
    <section className="real-workspace">
      <header>
        <span className="mobile-header-mark">旅</span>
        <div className="desktop-group-title"><small>我的群組　/　共同帳本</small><h2>{group?.name||'旅帳'}</h2></div>
        <label className="mobile-group-picker"><small>目前群組</small><select value={activeId||''} onChange={e=>setActiveId(e.target.value)}>{groups.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
        <button type="button" className="mobile-new-group" onClick={()=>setShowCreate(true)} aria-label="建立新群組" title="建立新群組"><Plus/></button>
        <div className="real-header-actions">
          {group?.members&&<div className="stack" aria-label={`${group.members.length} 位群組成員`}>{group.members.slice(0,5).map(p=><Person person={p} key={p.id} size={35}/>)}</div>}
          <button className="header-secondary" disabled={!group} onClick={()=>setShowInvite(true)}><Users/> 邀請成員</button>
          <button className="primary header-primary" disabled={!group||groupLoading} onClick={openNewExpense}><Plus/> 新增支出</button>
          <button className="mobile-header-avatar" aria-label="點擊頭像登出" onClick={()=>confirm('確定要登出嗎？')&&logout()}><Person person={me} size={38}/></button>
          <button className="mobile-logout" aria-label="登出" onClick={logout}><LogOut/></button>
        </div>
      </header>
      {!groups.length?<EmptyGroups create={()=>setShowCreate(true)}/>:groupError&&!group?<WorkspaceError message={groupError} retry={refreshGroup}/>:!group?<DashboardSkeleton/>:<GroupDashboard group={group} me={me} addExpense={openNewExpense} editExpense={expense=>{setEditingExpense(expense);setShowExpense(true)}} invite={()=>setShowInvite(true)} removeGroup={()=>groupDeleted(group)} refresh={refreshGroup} refreshing={groupLoading}/>}
    </section>
    {group&&<button className="mobile-expense-fab" onClick={openNewExpense} aria-label="新增支出"><Plus/><span>新增</span></button>}
    {notice&&<button type="button" className="toast" onClick={()=>setNotice('')} aria-live="polite" aria-label={`${notice}，點擊關閉`}><Check/>{notice}</button>}
    {showCreate&&<CreateGroup close={()=>setShowCreate(false)} done={created}/>} {showExpense&&group&&<AdvancedExpenseModal group={group} expense={editingExpense} close={()=>{setShowExpense(false);setEditingExpense(null)}} done={expenseAdded}/>} {showInvite&&group&&<InviteModal group={group} close={()=>setShowInvite(false)}/>}
  </div>
}

function EmptyGroups({create}){return <main className="empty-groups"><img src="/xiaoluo-avatar.png" alt="旅行成員頭像"/><span className="eyebrow">歡迎加入旅帳 TripTab</span><h1>先建立第一個分帳群組</h1><p>為這次活動取一個名字，再把邀請連結傳給同行的朋友。</p><button className="primary" onClick={create}><Plus/> 建立群組</button></main>}
function DashboardSkeleton(){return <main className="dashboard-skeleton" aria-label="正在載入群組資料" aria-busy="true"><div className="skeleton skeleton-hero"></div><div className="skeleton-stats">{[0,1,2].map(item=><div className="skeleton" key={item}></div>)}</div><div className="skeleton-grid"><div className="skeleton"></div><div className="skeleton"></div></div><span className="sr-only">正在載入群組資料</span></main>}
function WorkspaceError({message,retry}){const [retrying,setRetrying]=useState(false);const handleRetry=async()=>{setRetrying(true);try{await retry()}catch{}finally{setRetrying(false)}};return <main className="workspace-error" role="alert"><span><AlertCircle/></span><h1>群組資料暫時無法載入</h1><p>{message||'請檢查網路連線後再試一次。'}</p><button className="primary" disabled={retrying} onClick={handleRetry}>{retrying?<LoaderCircle/>:<RefreshCcw/>}{retrying?'重新載入中…':'重新載入'}</button></main>}
function GroupDashboard({group,me,addExpense,editExpense,invite,removeGroup,refresh,refreshing=false}){
 const [paying,setPaying]=useState(''),[deleting,setDeleting]=useState(''),[deletingGroup,setDeletingGroup]=useState(false),[showSettlementHelp,setShowSettlementHelp]=useState(false),[showBalances,setShowBalances]=useState(false),[actionError,setActionError]=useState('');
 const total=group.expenses.reduce((sum,e)=>sum+e.amountCents,0);const mine=group.balances.find(x=>x.id===me.id)?.balanceCents||0;
 const canPay=settlement=>settlement.from.id===me.id;
 const canManageFundPayment=settlement=>settlement.from.isFund&&group.ownerId===me.id&&settlement.to.id!==me.id;
 const canConfirm=settlement=>canPay(settlement)||canManageFundPayment(settlement);
 const markPaid=async settlement=>{setPaying(settlement.to.id);setActionError('');try{await api(`/api/groups/${group.id}/settlements`,{method:'POST',body:JSON.stringify({fromUserId:settlement.from.id,toUserId:settlement.to.id,amount:settlement.amountCents/100})});await refresh()}catch(error){setActionError(error.message)}finally{setPaying('')}};
 const removeExpense=async expense=>{if(!confirm(`確定要刪除「${expense.title}」嗎？刪除後無法復原。`))return;setDeleting(expense.id);setActionError('');try{await api(`/api/groups/${group.id}/expenses/${expense.id}`,{method:'DELETE'});await refresh()}catch(error){setActionError(error.message)}finally{setDeleting('')}};
 const deleteCurrentGroup=async()=>{if(!confirm(`確定要刪除群組「${group.name}」嗎？所有支出與結算都會一併刪除，且無法復原。`))return;setDeletingGroup(true);setActionError('');try{await removeGroup()}catch(error){setActionError(error.message);setDeletingGroup(false)}};
 return <main className={`real-dashboard ${refreshing?'is-refreshing':''}`} aria-busy={refreshing}>
  {refreshing&&<div className="workspace-progress" role="status"><span></span><span className="sr-only">正在更新群組資料</span></div>}
  {actionError&&<div className="inline-alert" role="alert"><AlertCircle/><span>{actionError}</span><button onClick={()=>setActionError('')} aria-label="關閉錯誤訊息"><X/></button></div>}
  <section className="group-hero" aria-labelledby="group-title">
   <div className="group-overview-copy"><span className="pill">{group.members.filter(x=>!x.isFund).length} 位成員 · TWD</span><h1 id="group-title">{group.name}</h1><p>{group.description||'一起記下每筆共同花費，最後輕鬆結清。'}</p></div>
   <div className="group-overview-side"><small>旅伴</small><div className="hero-members">{group.members.slice(0,7).map(p=><Person person={p} key={p.id} size={40}/>)}<button onClick={invite} aria-label="邀請新成員"><Plus/></button></div>{group.ownerId===me.id&&<details className="group-admin-menu"><summary><Settings2/> 群組設定</summary><div><p>刪除後，所有支出與結算都無法復原。</p><button className="danger-action" disabled={deletingGroup} onClick={deleteCurrentGroup}>{deletingGroup?<LoaderCircle/>:<Trash2/>}{deletingGroup?'刪除中…':'刪除群組'}</button></div></details>}</div>
  </section>
  <nav className="mobile-shortcuts" aria-label="群組快捷功能"><button onClick={()=>document.querySelector('.expense-panel')?.scrollIntoView({behavior:'smooth'})}><ReceiptText/><span>支出</span></button><button onClick={()=>setShowBalances(true)}><WalletCards/><span>結餘</span></button><button onClick={()=>document.querySelector('.settlements')?.scrollIntoView({behavior:'smooth'})}><Check/><span>結算</span></button><button onClick={invite}><Users/><span>邀請</span></button></nav>
  <div className="real-stats">
   <article className="metric-card"><span className="stat-icon green"><WalletCards/></span><div><small>我的餘額</small><h3 className={mine>=0?'positive':'negative'}>{mine>=0?'應收 ':'應付 '}{money(Math.abs(mine))}</h3><p>{mine===0?'目前沒有待結算款項':mine>0?'其他成員需要付給你':'你需要付給其他成員'}</p></div></article>
   <article className="metric-card"><span className="stat-icon orange"><ReceiptText/></span><div><small>群組總支出</small><h3>{money(total)}</h3><p>共 {group.expenses.length} 筆共同花費</p></div></article>
   <article className="metric-card settlement-stat"><span className="stat-icon"><Check/></span><div><small>待處理轉帳</small><h3>{group.settlements.length} 次</h3><p>已自動簡化轉帳路徑</p></div></article>
  </div>
  <div className="real-grid">
   <div className="activity-column">
    <section className="expense-panel" aria-labelledby="expense-title"><div className="section-head"><div><span className="section-kicker">支出明細</span><h2 id="expense-title">最近支出</h2><p>依新增時間排序，所有成員看到的資料保持一致。</p></div><div className="expense-actions"><span className="count-badge">{group.expenses.length} 筆</span><button className="primary" onClick={addExpense}><Plus/> 新增支出</button></div></div>{!group.expenses.length?<div className="empty-list"><ReceiptText/><b>還沒有任何支出</b><p>從第一筆共同花費開始建立清楚帳目。</p><button className="empty-primary" onClick={addExpense}><Plus/> 新增第一筆支出</button></div>:<><div className="record-table-head" aria-hidden="true"><span>項目</span><span>分攤資訊</span><span>金額</span><span>操作</span></div><div className="record-list">{group.expenses.map(e=><article key={e.id}><ExpenseCategory expense={e}/><div className="record-name"><b title={e.title}>{e.title}</b><small>{new Date(e.createdAt).toLocaleDateString('zh-TW')} · {e.payerName} {e.amountCents<0?'收到退款':'先付'} · {e.shareCount} 人分</small></div><div className="record-price"><b className={e.amountCents<0?'positive':''}>{money(e.amountCents)}</b><small>{e.payerCount>1?`${e.payerCount} 人共同付款`:`平均 ${money(Math.round(e.amountCents/e.shareCount))}`}</small></div>{(e.createdBy===me.id||group.ownerId===me.id)&&<div className="expense-row-actions"><button className="expense-edit" title="修改支出" aria-label={`修改 ${e.title}`} onClick={()=>editExpense(e)}><Pencil/></button><button className="expense-delete" title="刪除支出" aria-label={`刪除 ${e.title}`} disabled={deleting===e.id} onClick={()=>removeExpense(e)}>{deleting===e.id?<LoaderCircle/>:<Trash2/>}</button></div>}</article>)}</div></>}</section>
   </div>
   <aside className="settlements" aria-labelledby="settlement-title"><div className="settlement-heading"><div><span className="section-kicker">待辦事項</span><h2 id="settlement-title">結算</h2><p>簡化後轉帳 · 共 {group.settlements.length} 筆</p></div><button className="settlement-help-button" onClick={()=>setShowSettlementHelp(true)} aria-label="了解結算演算法"><CircleHelp/></button></div>{!group.settlements.length?<div className="all-clear"><Check/><b>目前都結清了</b><p>新增支出後，旅帳會在這裡整理最少轉帳路徑。</p></div>:<div className="settlement-list">{group.settlements.map((s,i)=><article className={`settlement-row ${canConfirm(s)?'payable':''}`} key={i}><span className={`settlement-status ${canConfirm(s)?'needs-action':''}`}>{canConfirm(s)?'待你處理':'等待對方'}</span><div className="settlement-person"><Person person={s.from} size={44}/><span className="settlement-person-copy"><small>付款人</small><b>{s.from.displayName}</b></span></div><div className="settlement-flow"><ArrowRight/><small>應付金額</small><strong>{money(s.amountCents)}</strong></div><div className="settlement-person receiver"><Person person={s.to} size={44}/><span className="settlement-person-copy"><small>收款人</small><b>{s.to.displayName}</b></span></div>{canConfirm(s)?<button disabled={Boolean(paying)} onClick={()=>markPaid(s)}>{paying===s.to.id?<><LoaderCircle/>處理中…</>:canManageFundPayment(s)?'從公費付款':'我已轉帳'}</button>:<div className="settlement-waiting">等待付款人轉帳</div>}</article>)}</div>}</aside>
   <SettlementHistory group={group}/>
  </div>
  {showSettlementHelp&&<SettlementHelp close={()=>setShowSettlementHelp(false)}/>} {showBalances&&<BalanceChart group={group} close={()=>setShowBalances(false)}/>}
 </main>
}
function SettlementHistory({group}){
 const rows=group.settlementHistory||[];
 const formatTime=value=>new Intl.DateTimeFormat('zh-TW',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
 return <section className="repayment-panel" aria-labelledby="repayment-title"><div className="section-head"><div><h2 id="repayment-title">還款紀錄</h2><p>已完成的實際轉帳 · 共 {rows.length} 筆</p></div><History aria-hidden="true"/></div>{!rows.length?<div className="repayment-empty"><History/><b>還沒有還款紀錄</b><p>完成第一筆轉帳後，紀錄會顯示在這裡。</p></div>:<div className="repayment-log">{rows.map(item=><article key={item.id}><div className="repayment-people"><Person person={item.from} size={38}/><ArrowRight/><Person person={item.to} size={38}/></div><div className="repayment-copy"><b>{item.from.displayName} 已還給 {item.to.displayName}</b><time dateTime={item.createdAt}>{formatTime(item.createdAt)}</time><small>由 {item.confirmedBy.displayName} 確認</small></div><strong>{money(item.amountCents)}</strong></article>)}</div>}</section>
}
function BalanceChart({group,close}){
 const rows=[...group.balances].sort((a,b)=>a.balanceCents-b.balanceCents);
 const maximum=Math.max(1,...rows.map(x=>Math.abs(x.balanceCents)));
 return <Modal close={close} label="群組結餘"><span className="eyebrow"><WalletCards/> Balance</span><h2>群組結餘</h2><p className="modal-copy">每個人的最終淨額：紅色代表需要付出，綠色代表可以收回。長度越長，金額越大。</p><div className="diverging-legend"><span>← 應付</span><i></i><span>應收 →</span></div><div className="diverging-chart">{rows.map(person=>{const value=person.balanceCents,width=value===0?0:Math.max(10,Math.round(Math.abs(value)/maximum*100)),member=<div className="diverging-member"><b>{person.displayName}</b><Person person={person} size={38}/></div>;return <div className={`diverging-row ${value<0?'is-debt':value>0?'is-credit':'is-zero'}`} key={person.id}><div className="diverging-left">{value<0?<span className="diverging-bar debt" style={{width:`${width}%`}}><strong>-{money(Math.abs(value))}</strong></span>:member}</div><div className="diverging-right">{value>0?<span className="diverging-bar credit" style={{width:`${width}%`}}><strong>+{money(value)}</strong></span>:value<0?member:<strong className="zero-amount">{money(0)}</strong>}</div></div>})}</div><div className="balance-check"><Check/> 所有人的結餘加總為 NT$ 0</div><button className="primary wide" onClick={close}>了解</button></Modal>
}
function SettlementHelp({close}){return <Modal close={close} label="結算說明"><span className="eyebrow"><CircleHelp/> 結算說明</span><h2>我們如何簡化轉帳？</h2><p className="modal-copy">系統會先把所有支出換算成每個人的最終淨額，再重新安排付款對象。原始帳目不會被修改，每個人最後付出或收到的總額也完全相同。</p><div className="settlement-example"><div className="example-title"><b>舉個例子</b><small>A、B、C 三人結算</small></div><div className="example-columns"><section><b>原始 · 3 筆</b><p>A → C　NT$ 100</p><p>B → C　NT$ 300</p><p>A → B　NT$ 50</p></section><ArrowRight/><section className="simplified"><b>簡化後 · 2 筆</b><p>A → C　NT$ 150</p><p>B → C　NT$ 250</p></section></div><div className="example-net"><span>A 應付 150</span><span>B 應付 250</span><span>C 應收 400</span></div></div><div className="algorithm-note"><b>目前採用的方式</b><p>先配對金額完全相同的人，再讓小額欠款者優先一次付清。目標是讓更多付款人只轉一次；較大的欠款者必要時可能拆成多筆，因此不保證全群總筆數是數學上的絕對最少。</p></div><button className="primary wide" onClick={close}>了解</button></Modal>}
function Modal({children,close,label='對話視窗'}){const dialogRef=useRef(null),closeRef=useRef(close),returnFocus=useRef(document.activeElement);closeRef.current=close;useEffect(()=>{const dialog=dialogRef.current,focusable='button:not([disabled]), a[href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])';const initialTimer=setTimeout(()=>{if(dialog&&!dialog.contains(document.activeElement))dialog.querySelector(focusable)?.focus()},0);const onKeyDown=event=>{if(event.key==='Escape'){event.preventDefault();closeRef.current();return}if(event.key!=='Tab'||!dialog)return;const items=[...dialog.querySelectorAll(focusable)].filter(item=>item.getClientRects().length);if(!items.length)return;const first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};document.addEventListener('keydown',onKeyDown);return()=>{clearTimeout(initialTimer);document.removeEventListener('keydown',onKeyDown);returnFocus.current?.focus?.()}},[]);return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div ref={dialogRef} className="modal real-modal" role="dialog" aria-modal="true" aria-label={label}><button type="button" className="modal-x" onClick={close} aria-label="關閉對話視窗"><X/></button>{children}</div></div>}
function CreateGroup({close,done}){const [name,setName]=useState(''),[description,setDescription]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const submit=async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{done(await api('/api/groups',{method:'POST',body:JSON.stringify({name,description})}))}catch(err){setError(err.message);setBusy(false)}};return <Modal close={close} label="建立分帳群組"><span className="eyebrow">新的共同帳本</span><h2>建立分帳群組</h2><p className="modal-copy">先為這次旅行取一個容易辨識的名稱，建立後即可邀請旅伴。</p><form onSubmit={submit}><label>群組名稱 <span className="required-mark" aria-hidden="true">*</span><input autoFocus maxLength="60" value={name} onChange={e=>setName(e.target.value)} placeholder="例如：花蓮三天兩夜" required aria-invalid={Boolean(error&&!name.trim())}/><small className="field-help">最多 60 個字，建議包含地點或日期。</small></label><label>簡短說明<input maxLength="200" value={description} onChange={e=>setDescription(e.target.value)} placeholder="例如：14 人畢旅共同花費"/><small className="field-help">選填，讓旅伴快速確認群組用途。</small></label>{error&&<p className="form-error" role="alert"><AlertCircle/>{error}</p>}<div className="form-actions"><button type="button" className="secondary-button" onClick={close} disabled={busy}>取消</button><button className="primary" disabled={busy||!name.trim()}>{busy?<LoaderCircle/>:<Plus/>}{busy?'建立中…':'建立群組'}</button></div></form></Modal>}
function ExpenseModal({group,close,done}){
 const [title,setTitle]=useState(''),[amount,setAmount]=useState(''),[payerId,setPayerId]=useState(group.members[0]?.id),[category,setCategory]=useState('餐飲'),[selected,setSelected]=useState(group.members.map(x=>x.id)),[mode,setMode]=useState('equal'),[custom,setCustom]=useState({}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const toggle=id=>setSelected(old=>old.includes(id)?old.filter(x=>x!==id):[...old,id]);
 const customTotal=selected.reduce((sum,id)=>sum+Number(custom[id]||0),0),difference=Number(amount||0)-customTotal;
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const payload={title,amount,payerId,category};if(mode==='equal')payload.participantIds=selected;else payload.shares=selected.map(userId=>({userId,amount:Number(custom[userId]||0)}));await api(`/api/groups/${group.id}/expenses`,{method:'POST',body:JSON.stringify(payload)});done()}catch(err){setError(err.message);setBusy(false)}};
 return <Modal close={close}><span className="eyebrow">共同花費</span><h2>新增一筆支出</h2><form onSubmit={submit}><label>項目名稱<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="例如：晚餐" required/></label><div className="form-two"><label>金額<input type="number" min="1" step="1" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="NT$ 0" required/></label><label>分類<select value={category} onChange={e=>setCategory(e.target.value)}><option>餐飲</option><option>住宿</option><option>交通</option><option>購物</option><option>其他</option></select></label></div><label>誰先付款？<select value={payerId} onChange={e=>setPayerId(e.target.value)}>{group.members.map(p=><option value={p.id} key={p.id}>{p.displayName}</option>)}</select></label><div className="split-mode"><button type="button" className={mode==='equal'?'active':''} onClick={()=>setMode('equal')}>平均分攤</button><button type="button" className={mode==='custom'?'active':''} onClick={()=>setMode('custom')}>自訂金額</button></div><label>哪些人一起分？ <small>已選 {selected.length}／{group.members.length} 人</small></label><div className={'participant-grid '+(mode==='custom'?'custom':'')}>{group.members.map(p=><div className={'participant-item '+(selected.includes(p.id)?'selected':'')} key={p.id}><button type="button" onClick={()=>toggle(p.id)}><Person person={p} size={31}/><span>{p.displayName}</span>{selected.includes(p.id)&&<Check/>}</button>{mode==='custom'&&selected.includes(p.id)&&<div className="share-input"><span>NT$</span><input type="number" min="1" step="1" value={custom[p.id]||''} onChange={e=>setCustom(old=>({...old,[p.id]:e.target.value}))} placeholder="0"/></div>}</div>)}</div>{mode==='custom'&&<div className={'share-summary '+(difference===0?'balanced':'')}><span>已分配 NT$ {customTotal.toLocaleString()}</span><b>{difference===0?'金額吻合 ✓':`還差 NT$ ${difference.toLocaleString()}`}</b></div>}{error&&<p className="form-error">{error}</p>}<button className="primary wide" disabled={busy||!selected.length||(mode==='custom'&&difference!==0)}>{busy?<LoaderCircle/>:<ReceiptText/>}{mode==='equal'?`由 ${selected.length} 人平均分攤`:'依自訂金額儲存'}</button></form></Modal>}
function InviteModal({group,close}){const link=`${location.origin}/invite/${group.inviteToken}`;const [copied,setCopied]=useState(false),[copyError,setCopyError]=useState('');const copy=async()=>{setCopyError('');try{await navigator.clipboard.writeText(link);setCopied(true)}catch{setCopyError('無法自動複製，請手動選取上方連結。')}};return <Modal close={close} label="邀請成員"><span className="eyebrow">邀請成員</span><h2>把連結傳到 LINE 群組</h2><p className="modal-copy">朋友點開後使用 LINE 登入，就會自動加入「{group.name}」。</p><div className="invite-link"><Link2/><span>{link}</span></div>{copyError&&<p className="form-error" role="alert"><AlertCircle/>{copyError}</p>}<button className="line-share" onClick={()=>location.href=`https://line.me/R/share?text=${encodeURIComponent(`加入「${group.name}」一起分帳：${link}`)}`}><DoorOpen/> 用 LINE 分享</button><button className="copy-link" onClick={copy} aria-live="polite">{copied?<Check/>:<Clipboard/>}{copied?'已複製邀請連結':'複製邀請連結'}</button></Modal>}
