import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {ArrowRight,Check,Clipboard,DoorOpen,Link2,LoaderCircle,LogOut,Pencil,Plus,ReceiptText,Users,WalletCards,X} from 'lucide-react';
import {AdvancedExpenseModal,FundModal} from './AdvancedExpenseModal.jsx';

const api=async(url,options={})=>{const response=await fetch(url,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});if(response.status===401)throw Object.assign(new Error('unauthorized'),{status:401});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'操作失敗');return data};
const money=cents=>`NT$ ${Math.round(Number(cents||0)/100).toLocaleString()}`;
function Logo(){return <div className="brand"><span className="brandmark"><span>東</span></span><b>東大小羅</b></div>}
function Person({person,size=36}){return person?.isFund?<span className="avatar fund-avatar" style={{width:size,height:size}}>🪙</span>:person?.pictureUrl?<img className="avatar" src={person.pictureUrl} style={{width:size,height:size}} referrerPolicy="no-referrer"/>:<span className="avatar initial" style={{width:size,height:size,background:'#1f9d69'}}>{person?.displayName?.slice(0,1)||'羅'}</span>}

export default function ProductApp({Home}){
  const [me,setMe]=useState(null),[groups,setGroups]=useState([]),[activeId,setActiveId]=useState(null),[group,setGroup]=useState(null),[loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[showCreate,setShowCreate]=useState(false),[showExpense,setShowExpense]=useState(false),[editingExpense,setEditingExpense]=useState(null),[showInvite,setShowInvite]=useState(false),[showFund,setShowFund]=useState(false);
  const inviteToken=location.pathname.startsWith('/invite/')?location.pathname.split('/')[2]:null;
  const refreshGroups=useCallback(async()=>{const list=await api('/api/groups');setGroups(list);setActiveId(current=>current||list[0]?.id||null);return list},[]);
  useEffect(()=>{api('/api/me').then(async user=>{setMe(user);const list=await refreshGroups();if(inviteToken){const joined=await api(`/api/invites/${encodeURIComponent(inviteToken)}/join`,{method:'POST'});setActiveId(joined.groupId);await refreshGroups();history.replaceState({},'', '/app');setNotice('已成功加入群組！')}}).catch(error=>{if(error.status!==401)setNotice(error.message)}).finally(()=>setLoading(false))},[]);
  const refreshGroup=useCallback(async()=>{if(!activeId){setGroup(null);return}setGroup(await api(`/api/groups/${activeId}`))},[activeId]);
  useEffect(()=>{if(me&&activeId)refreshGroup().catch(e=>setNotice(e.message))},[me,activeId,refreshGroup]);
  const login=()=>{const returnTo=inviteToken?location.pathname:'/app';location.href=`/api/auth/line?returnTo=${encodeURIComponent(returnTo)}`};
  const logout=async()=>{await api('/api/auth/logout',{method:'POST'});setMe(null);setGroups([]);setGroup(null);history.replaceState({},'','/')};
  const created=async data=>{setShowCreate(false);await refreshGroups();setActiveId(data.id);history.replaceState({},'','/app')};
  const expenseAdded=async()=>{setShowExpense(false);setEditingExpense(null);await refreshGroup()};
  if(loading)return <div className="page-loading"><LoaderCircle/><p>小羅正在整理帳本…</p></div>;
  if(!me)return <div><Home enter={login}/>{inviteToken&&<div className="invite-float"><Link2/><div><b>你收到一個群組邀請</b><small>使用 LINE 登入後即可加入</small></div><button onClick={login}>登入加入</button></div>}</div>;
  return <div className="real-app">
    <aside className="real-side"><Logo/><div className="login-user"><Person person={me} size={46}/><div><b>{me.displayName}</b><small>LINE 帳號已連結</small></div></div><div className="side-label">我的群組</div><div className="group-switcher">{groups.map((item,index)=><button className={activeId===item.id?'active':''} key={item.id} onClick={()=>setActiveId(item.id)}><span>{['🌊','⛰️','🍜','🏠'][index%4]}</span><div><b>{item.name}</b><small>{item.memberCount} 位成員</small></div></button>)}</div><button className="new-group" onClick={()=>setShowCreate(true)}><Plus/> 建立新群組</button><button className="logout" onClick={logout}><LogOut/> 登出</button></aside>
<section className="real-workspace"><header><span className="mobile-header-mark">東</span><div className="desktop-group-title"><small>共同帳本</small><h2>{group?.name||'東大小羅'}</h2></div><label className="mobile-group-picker"><small>目前群組</small><select value={activeId||''} onChange={e=>setActiveId(e.target.value)}>{groups.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="real-header-actions">{group?.members&&<div className="stack">{group.members.slice(0,5).map(p=><Person person={p} key={p.id} size={35}/>)}</div>}<button className="invite" disabled={!group} onClick={()=>setShowInvite(true)}><Users/> 邀請成員</button><button className="mobile-header-avatar" aria-label="點擊頭像登出" onClick={()=>confirm('確定要登出嗎？')&&logout()}><Person person={me} size={38}/></button><button className="mobile-logout" aria-label="登出" onClick={logout}><LogOut/></button></div></header>
    {!groups.length?<EmptyGroups create={()=>setShowCreate(true)}/>:!group?<div className="page-loading"><LoaderCircle/></div>:<GroupDashboard group={group} me={me} addExpense={()=>{setEditingExpense(null);setShowExpense(true)}} editExpense={expense=>{setEditingExpense(expense);setShowExpense(true)}} invite={()=>setShowInvite(true)} manageFund={()=>setShowFund(true)} refresh={refreshGroup}/>}</section>
    {group&&<button className="mobile-expense-fab" onClick={()=>{setEditingExpense(null);setShowExpense(true)}} aria-label="新增支出"><Plus/><span>新增</span></button>}
    {notice&&<div className="toast" onClick={()=>setNotice('')}><Check/>{notice}</div>}
    {showCreate&&<CreateGroup close={()=>setShowCreate(false)} done={created}/>} {showExpense&&group&&<AdvancedExpenseModal group={group} expense={editingExpense} close={()=>{setShowExpense(false);setEditingExpense(null)}} done={expenseAdded}/>} {showInvite&&group&&<InviteModal group={group} close={()=>setShowInvite(false)}/>} {showFund&&group&&<FundModal group={group} me={me} close={()=>setShowFund(false)} done={async()=>{setShowFund(false);await refreshGroup()}}/>}
  </div>
}

function EmptyGroups({create}){return <main className="empty-groups"><img src="/xiaoluo-avatar.png"/><span className="eyebrow">歡迎加入東大小羅</span><h1>先建立第一個分帳群組</h1><p>為這次活動取一個名字，再把邀請連結傳給另外 13 位朋友。</p><button className="primary" onClick={create}><Plus/> 建立群組</button></main>}
function GroupDashboard({group,me,addExpense,editExpense,invite,manageFund,refresh}){
 const [paying,setPaying]=useState('');
 const total=group.expenses.reduce((sum,e)=>sum+e.amountCents,0);const mine=group.balances.find(x=>x.id===me.id)?.balanceCents||0;
 const canPay=settlement=>settlement.from.id===me.id||(settlement.from.isFund&&group.ownerId===me.id);
 const markPaid=async settlement=>{setPaying(settlement.to.id);try{await api(`/api/groups/${group.id}/settlements`,{method:'POST',body:JSON.stringify({fromUserId:settlement.from.id,toUserId:settlement.to.id,amount:settlement.amountCents/100})});await refresh()}finally{setPaying('')}};
 return <main className="real-dashboard"><section className="group-hero"><div><span className="pill">{group.members.filter(x=>!x.isFund).length} 位成員 · TWD</span><h1>{group.name}</h1><p>{group.description||'一起記下每筆共同花費，最後輕鬆結清。'}</p><div className="hero-members">{group.members.slice(0,7).map(p=><Person person={p} key={p.id} size={42}/>)}<button onClick={invite}><Plus/></button></div></div><img src="/xiaoluo-avatar.png"/></section>
 <nav className="mobile-shortcuts" aria-label="群組快捷功能"><button onClick={()=>document.querySelector('.expense-panel')?.scrollIntoView({behavior:'smooth'})}><ReceiptText/><span>支出</span></button><button onClick={()=>document.querySelector('.real-stats')?.scrollIntoView({behavior:'smooth'})}><WalletCards/><span>餘額</span></button><button onClick={()=>document.querySelector('.settlements')?.scrollIntoView({behavior:'smooth'})}><Check/><span>結算</span></button><button onClick={manageFund}><WalletCards/><span>公費</span></button><button onClick={invite}><Users/><span>邀請</span></button></nav>
 <div className="real-stats"><article><span className="stat-icon green"><WalletCards/></span><div><small>我的餘額</small><h3 className={mine>=0?'positive':'negative'}>{mine>=0?'應收 ':'應付 '}{money(Math.abs(mine))}</h3></div></article><article><span className="stat-icon orange"><ReceiptText/></span><div><small>群組總支出</small><h3>{money(total)}</h3></div></article><article className="settlement-stat"><small>最少轉帳次數</small><h3>{group.settlements.length} 次</h3><span>小羅已自動簡化債務</span></article></div>
<div className="real-grid"><section className="expense-panel"><div className="section-head"><div><h2>最近支出</h2><p>所有成員看到的資料會保持一致</p></div><div className="expense-actions"><button className="fund-button" onClick={manageFund}>🪙 公費</button><button className="primary" onClick={addExpense}><Plus/> 新增支出</button></div></div>{!group.expenses.length?<div className="empty-list"><ReceiptText/><b>還沒有任何支出</b><p>新增第一筆共同花費吧！</p></div>:<div className="record-list">{group.expenses.map(e=><article key={e.id}><span className="record-icon">{e.amountCents<0?'↩️':e.category==='餐飲'?'🍜':e.category==='住宿'?'🏠':e.category==='交通'?'🚗':'🧾'}</span><div className="record-name"><b>{e.title}</b><small>{new Date(e.createdAt).toLocaleDateString('zh-TW')} · {e.payerName} {e.amountCents<0?'收到退款':'先付'} · {e.shareCount} 人分</small></div><div className="record-price"><b className={e.amountCents<0?'positive':''}>{money(e.amountCents)}</b><small>{e.payerCount>1?`${e.payerCount} 人共同付款`:`平均 ${money(Math.round(e.amountCents/e.shareCount))}`}</small></div>{(e.createdBy===me.id||group.ownerId===me.id)&&<button className="expense-edit" title="修改支出" aria-label={`修改 ${e.title}`} onClick={()=>editExpense(e)}><Pencil/></button>}</article>)}</div>}</section>
 <aside className="settlements"><div className="settlement-heading"><div><h2>結算</h2><p>最少轉帳次數 · 共 {group.settlements.length} 筆</p></div><Check/></div>{!group.settlements.length?<div className="all-clear"><Check/><b>目前都結清了</b></div>:<div className="settlement-list">{group.settlements.map((s,i)=><article className={`settlement-row ${canPay(s)?'payable':''}`} key={i}><div className="settlement-person"><Person person={s.from} size={44}/><span><small>付款人</small><b>{s.from.displayName}</b></span></div><div className="settlement-flow"><ArrowRight/><small>應付金額</small><strong>{money(s.amountCents)}</strong></div><div className="settlement-person receiver"><Person person={s.to} size={44}/><span><small>收款人</small><b>{s.to.displayName}</b></span></div>{canPay(s)?<button disabled={Boolean(paying)} onClick={()=>markPaid(s)}>{paying===s.to.id?'處理中…':'我已轉帳'}</button>:<div className="settlement-waiting">等待 {s.from.displayName} 付款</div>}</article>)}</div>}</aside></div></main>
}
function Modal({children,close}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal real-modal"><button className="modal-x" onClick={close}><X/></button>{children}</div></div>}
function CreateGroup({close,done}){const [name,setName]=useState(''),[description,setDescription]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const submit=async e=>{e.preventDefault();setBusy(true);try{done(await api('/api/groups',{method:'POST',body:JSON.stringify({name,description})}))}catch(err){setError(err.message);setBusy(false)}};return <Modal close={close}><span className="eyebrow">新的共同帳本</span><h2>建立分帳群組</h2><form onSubmit={submit}><label>群組名稱<input autoFocus maxLength="60" value={name} onChange={e=>setName(e.target.value)} placeholder="例如：花蓮三天兩夜" required/></label><label>簡短說明<input maxLength="200" value={description} onChange={e=>setDescription(e.target.value)} placeholder="例如：14 人畢旅共同花費"/></label>{error&&<p className="form-error">{error}</p>}<button className="primary wide" disabled={busy}>{busy?<LoaderCircle/>:<Plus/>}建立群組</button></form></Modal>}
function ExpenseModal({group,close,done}){
 const [title,setTitle]=useState(''),[amount,setAmount]=useState(''),[payerId,setPayerId]=useState(group.members[0]?.id),[category,setCategory]=useState('餐飲'),[selected,setSelected]=useState(group.members.map(x=>x.id)),[mode,setMode]=useState('equal'),[custom,setCustom]=useState({}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const toggle=id=>setSelected(old=>old.includes(id)?old.filter(x=>x!==id):[...old,id]);
 const customTotal=selected.reduce((sum,id)=>sum+Number(custom[id]||0),0),difference=Number(amount||0)-customTotal;
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const payload={title,amount,payerId,category};if(mode==='equal')payload.participantIds=selected;else payload.shares=selected.map(userId=>({userId,amount:Number(custom[userId]||0)}));await api(`/api/groups/${group.id}/expenses`,{method:'POST',body:JSON.stringify(payload)});done()}catch(err){setError(err.message);setBusy(false)}};
 return <Modal close={close}><span className="eyebrow">共同花費</span><h2>新增一筆支出</h2><form onSubmit={submit}><label>項目名稱<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="例如：晚餐" required/></label><div className="form-two"><label>金額<input type="number" min="1" step="1" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="NT$ 0" required/></label><label>分類<select value={category} onChange={e=>setCategory(e.target.value)}><option>餐飲</option><option>住宿</option><option>交通</option><option>購物</option><option>其他</option></select></label></div><label>誰先付款？<select value={payerId} onChange={e=>setPayerId(e.target.value)}>{group.members.map(p=><option value={p.id} key={p.id}>{p.displayName}</option>)}</select></label><div className="split-mode"><button type="button" className={mode==='equal'?'active':''} onClick={()=>setMode('equal')}>平均分攤</button><button type="button" className={mode==='custom'?'active':''} onClick={()=>setMode('custom')}>自訂金額</button></div><label>哪些人一起分？ <small>已選 {selected.length}／{group.members.length} 人</small></label><div className={'participant-grid '+(mode==='custom'?'custom':'')}>{group.members.map(p=><div className={'participant-item '+(selected.includes(p.id)?'selected':'')} key={p.id}><button type="button" onClick={()=>toggle(p.id)}><Person person={p} size={31}/><span>{p.displayName}</span>{selected.includes(p.id)&&<Check/>}</button>{mode==='custom'&&selected.includes(p.id)&&<div className="share-input"><span>NT$</span><input type="number" min="1" step="1" value={custom[p.id]||''} onChange={e=>setCustom(old=>({...old,[p.id]:e.target.value}))} placeholder="0"/></div>}</div>)}</div>{mode==='custom'&&<div className={'share-summary '+(difference===0?'balanced':'')}><span>已分配 NT$ {customTotal.toLocaleString()}</span><b>{difference===0?'金額吻合 ✓':`還差 NT$ ${difference.toLocaleString()}`}</b></div>}{error&&<p className="form-error">{error}</p>}<button className="primary wide" disabled={busy||!selected.length||(mode==='custom'&&difference!==0)}>{busy?<LoaderCircle/>:<ReceiptText/>}{mode==='equal'?`由 ${selected.length} 人平均分攤`:'依自訂金額儲存'}</button></form></Modal>}
function InviteModal({group,close}){const link=`${location.origin}/invite/${group.inviteToken}`;const [copied,setCopied]=useState(false);const copy=async()=>{await navigator.clipboard.writeText(link);setCopied(true)};return <Modal close={close}><span className="eyebrow">邀請成員</span><h2>把連結傳到 LINE 群組</h2><p className="modal-copy">朋友點開後使用 LINE 登入，就會自動加入「{group.name}」。</p><div className="invite-link"><Link2/><span>{link}</span></div><button className="line-share" onClick={()=>location.href=`https://line.me/R/share?text=${encodeURIComponent(`加入「${group.name}」一起分帳：${link}`)}`}><DoorOpen/> 用 LINE 分享</button><button className="copy-link" onClick={copy}>{copied?<Check/>:<Clipboard/>}{copied?'已複製邀請連結':'複製邀請連結'}</button></Modal>}
