import React from 'react';
import {WarningCircleIcon} from '@phosphor-icons/react/dist/csr/WarningCircle';
import {ArrowsClockwiseIcon} from '@phosphor-icons/react/dist/csr/ArrowsClockwise';
import {ArrowDownIcon} from '@phosphor-icons/react/dist/csr/ArrowDown';
import {ArrowLeftIcon} from '@phosphor-icons/react/dist/csr/ArrowLeft';
import {ArrowRightIcon} from '@phosphor-icons/react/dist/csr/ArrowRight';
import {ArrowUpIcon} from '@phosphor-icons/react/dist/csr/ArrowUp';
import {ArrowsDownUpIcon} from '@phosphor-icons/react/dist/csr/ArrowsDownUp';
import {BellIcon} from '@phosphor-icons/react/dist/csr/Bell';
import {BuildingsIcon} from '@phosphor-icons/react/dist/csr/Buildings';
import {CaretDownIcon} from '@phosphor-icons/react/dist/csr/CaretDown';
import {CaretLeftIcon} from '@phosphor-icons/react/dist/csr/CaretLeft';
import {CaretRightIcon} from '@phosphor-icons/react/dist/csr/CaretRight';
import {ChartBarIcon} from '@phosphor-icons/react/dist/csr/ChartBar';
import {ChatCircleTextIcon} from '@phosphor-icons/react/dist/csr/ChatCircleText';
import {CheckIcon} from '@phosphor-icons/react/dist/csr/Check';
import {CopyIcon} from '@phosphor-icons/react/dist/csr/Copy';
import {ClockIcon} from '@phosphor-icons/react/dist/csr/Clock';
import {ClockCounterClockwiseIcon} from '@phosphor-icons/react/dist/csr/ClockCounterClockwise';
import {CurrencyCircleDollarIcon} from '@phosphor-icons/react/dist/csr/CurrencyCircleDollar';
import {FlaskIcon} from '@phosphor-icons/react/dist/csr/Flask';
import {GearSixIcon} from '@phosphor-icons/react/dist/csr/GearSix';
import {HouseIcon} from '@phosphor-icons/react/dist/csr/House';
import {InfoIcon} from '@phosphor-icons/react/dist/csr/Info';
import {LinkIcon} from '@phosphor-icons/react/dist/csr/Link';
import {ListIcon} from '@phosphor-icons/react/dist/csr/List';
import {MagnifyingGlassIcon} from '@phosphor-icons/react/dist/csr/MagnifyingGlass';
import {PencilSimpleIcon} from '@phosphor-icons/react/dist/csr/PencilSimple';
import {PlayIcon} from '@phosphor-icons/react/dist/csr/Play';
import {PlusIcon} from '@phosphor-icons/react/dist/csr/Plus';
import {QuestionIcon} from '@phosphor-icons/react/dist/csr/Question';
import {ReceiptIcon} from '@phosphor-icons/react/dist/csr/Receipt';
import {ShareNetworkIcon} from '@phosphor-icons/react/dist/csr/ShareNetwork';
import {ShieldCheckIcon} from '@phosphor-icons/react/dist/csr/ShieldCheck';
import {SignOutIcon} from '@phosphor-icons/react/dist/csr/SignOut';
import {SparkleIcon} from '@phosphor-icons/react/dist/csr/Sparkle';
import {SpinnerGapIcon} from '@phosphor-icons/react/dist/csr/SpinnerGap';
import {TrashIcon} from '@phosphor-icons/react/dist/csr/Trash';
import {UserPlusIcon} from '@phosphor-icons/react/dist/csr/UserPlus';
import {UserCircleIcon} from '@phosphor-icons/react/dist/csr/UserCircle';
import {UsersThreeIcon} from '@phosphor-icons/react/dist/csr/UsersThree';
import {WalletIcon} from '@phosphor-icons/react/dist/csr/Wallet';
import {XIcon} from '@phosphor-icons/react/dist/csr/X';

export const AlertCircle=WarningCircleIcon;
export const ArrowDown=ArrowDownIcon;
export const ArrowLeft=ArrowLeftIcon;
export const ArrowRight=ArrowRightIcon;
export const ArrowUp=ArrowUpIcon;
export const ArrowUpDown=ArrowsDownUpIcon;
export const BarChart3=ChartBarIcon;
export const Bell=BellIcon;
export const Building2=BuildingsIcon;
export const Check=CheckIcon;
export const ChevronDown=CaretDownIcon;
export const ChevronLeft=CaretLeftIcon;
export const ChevronRight=CaretRightIcon;
export const CircleDollarSign=CurrencyCircleDollarIcon;
export const CircleHelp=QuestionIcon;
export const Clipboard=CopyIcon;
export const Clock3=ClockIcon;
export const DoorOpen=ShareNetworkIcon;
export const FlaskConical=FlaskIcon;
export const History=ClockCounterClockwiseIcon;
export const Home=HouseIcon;
export const Info=InfoIcon;
export const Link2=LinkIcon;
export const LogOut=SignOutIcon;
export const Menu=ListIcon;
export const MessageCircle=ChatCircleTextIcon;
export const Pencil=PencilSimpleIcon;
export const Play=PlayIcon;
export const Plus=PlusIcon;
export const ReceiptText=ReceiptIcon;
export const RefreshCcw=ArrowsClockwiseIcon;
export const Search=MagnifyingGlassIcon;
export const Settings2=GearSixIcon;
export const ShieldCheck=ShieldCheckIcon;
export const Sparkles=SparkleIcon;
export const Trash2=TrashIcon;
export const UserPlus=UserPlusIcon;
export const UserRound=UserCircleIcon;
export const Users=UsersThreeIcon;
export const WalletCards=WalletIcon;
export const X=XIcon;

export function LoaderCircle({className='',...props}){
  return <SpinnerGapIcon {...props} className={`icon-spinner ${className}`.trim()}/>;
}
